dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python
  - sudo apt-get install -y build-essential
  - npm install -g ffmpeg-binaries
install:
  - npm install
before_script:
  - cp settings/credentials_example.json settings/credentials.json
  - cp settings/config_example.json settings/config.json
  - echo "[]" > data/favouriteSongs.json
script:
  - npm test
