branches:
  only:
    - master
    - dev
skip_tags: true
skip_commits:
  message: /(\[skip appveyor\]|\[appveyor skip\])/
image:
  - Visual Studio 2015
  - Visual Studio 2017
clone_depth: 1
environment:
  nodejs_version: "7"
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test:lint
  - npm run test:boot
platform: x64
deploy: off
